version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

#  mysql:
#          build:
#              context: "docker/mysql/"
#          ports:
#              - "3306:3306"
#          environment:
#              - MYSQL_DATABASE=sampledb
#              - MYSQL_HOST=localhost
#              - MYSQL_USER=root
#              - MYSQL_ROOT_PASSWORD=root
#          volumes:
#              - "storage:/var/lib/mysql"
#              - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"

  db:
    build:
      context: "./docker/mysql"
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=sampledb
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
